apiVersion: v1
kind: Service
metadata:
  labels:
  name: web-server-service
  namespace: web-server
spec:
  ports:
  - port: 18080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
